### ISSUE TITLE
Unresolved reference on variables

### ISSUE THREAD

**Issue by jurgenbrouwer** [karollewandowski/aem-intellij-plugin#171]
It seems not all bound HTL variables are resolved.

For example "caconfig" provided by [Apache Sling Context-Aware Configuration](https://sling.apache.org/documentation/bundles/context-aware-configuration/context-aware-configuration.html#accessing-configuration-from-htl-sightly-templates) is unresolved:
<img width="436" alt="caconfig-not-resolved" src="https://user-images.githubusercontent.com/1295167/50628128-fab00100-0f36-11e9-9343-63ef064ac0eb.png">

Another issue is when variables are used before the data-sly-use statement in the code.
The data-sly-use variables are available in the whole file, the following piece of code is valid HTL but the variable is incorrectly marked as unresolved:
<img width="680" alt="data-sly-use-not-resolved" src="https://user-images.githubusercontent.com/1295167/50628269-afe2b900-0f37-11e9-8a0e-0def1ba81aa0.png">

Tested on AEM 6.3.3 with HTL 1.4.34

**Comment by karollewandowski** [comment]
Thank you for reporting this.

I have the first issue in my non-public issues tracker already, but I'm not sure about the correct solution yet. I think that I have to implement a mechanism for registering custom global variables. They can be provided not only by official Sling or AEM bundles but also by companies internal bundles (I know people working on projects covering such case). It would be good to detect official bundles used in a project and provide known variables exposed by them, so developers don't have to do anything.


I don't agree the second one is an issue. Please see [the use block specification](https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#221-use):

> - **Scope**: The identifier set by the data-sly-use block element is global to the script and can be used anywhere **after** its declaration

Even if it works in HTL implementation you use, we should follow specification, because it may change in future. I analyzed variables scopes very deeply and even contributed to HTL spec in this scope, so it should work correctly (I'm not saying there is not hidden bug though :-) ).
Please check `data-sly-repeat` block for comparison - its variable can be used before a declaration, but only in the same element/tag.

**Comment by karollewandowski** [comment]
After rethinking I'm not sure the second one is not an issue. It seems inconsistent with mentioned by me `data-sly-repeat`'s behavior despite different scope descriptions. Maybe I understand "after declaration" too literally.
Netcentric's [AEM HTL Style Guide rule 4.7](https://github.com/Netcentric/aem-htl-style-guide#4.7) tells to place block statements always after the normal attributes (I guess you follow it), but it lacks explicit reason and I'm not sure if it's a good one.
I think that "after declaration" meaning should be clarified on [htl-spec](https://github.com/adobe/htl-spec) repository, so if you could create such issue there I would be very grateful. If they allow your example to exist I don't see any objections to implement it in plugin.

**Comment by jurgenbrouwer** [comment]
> I have the first issue in my non-public issues tracker already, but I'm not sure about the correct solution yet. I think that I have to implement a mechanism for registering custom global variables. They can be provided not only by official Sling or AEM bundles but also by companies internal bundles (I know people working on projects covering such case). It would be good to detect official bundles used in a project and provide known variables exposed by them, so developers don't have to do anything.

That would be awesome,  but I guess it needs some digging in all the dependencies to get all the possible global variables. I would be satisfied with manually adding/acknowledging these "exceptions", if that's even a thing.

> Netcentric's AEM HTL Style Guide rule 4.7 tells to place block statements always after the normal attributes (I guess you follow it), but it lacks explicit reason and I'm not sure if it's a good one.
I think that "after declaration" meaning should be clarified on htl-spec repository, so if you could create such issue there I would be very grateful. If they allow your example to exist I don't see any objections to implement it in the plugin.

My colleagues and I indeed follow these guidelines. We had another discussion about it today, but it still makes sense though to put all normal attributes first. I must admit that I personally feel that using the variable before binding it doesn't feel natural. But yeah, it's not clear whether or not it's intentionally working that way. I'll try to get some clarification on the other repository. Thanks for the additional info!

**Comment by karollewandowski** [comment]
> I'll try to get some clarification on the other repository.

Great, thanks, I appreciate it. Please do not forget about `data-sly-set` and `data-sly-test` blocks.

> We had another discussion about it today, but it still makes sense though to put all normal attributes first.

I agree it is not intuitive and in my opinion **very** hard to read. May I know what arguments your colleagues have? Maybe it will help me to understand the need of such rule.
Personally, I would make the rule 4.7 exactly the opposite - to always place HTL blocks before standard HTML attributes - neither blocks nor expressions depend on standard attributes, but standard attributes values very often depend on HTL block statements and it is natural to read code from left to right, to get definition/declaration of something at first and then use it.
Maybe it will be worth of creating an issue in style guide repo to change or remove it. They once agreed about removing one rule about self-closing `<sly/>` tag (that people from my team blindly followed), so they seem open for reasonable changes even for old rules.

**Comment by karollewandowski** [comment]
It looks like rule will be probably changed, but I decided to go with resolving variables used before the declaration, but only on the same element. It breaks specification a bit but is consistent with Sling implementation and I guess that there are a lot of projects following 4.7, so it will be a bit easier to work on them.
Additionally, I will add configurable (enabled by default) error inspection for such usages with the fix to automatically move usages after declarations.
It should be released in about 2-3 weeks (I have a few more tasks to implement in current milestone) and will include custom global variables support (I already implemented out of the box `caconfig` support for AEM 6.2+).

**Comment by karollewandowski** [comment]
@jurgenbrouwer, version 0.10 is released and it covers discussed improvements partially:
- `caconfig` added to global objects list
- variables used before declaration are resolved according to Sling implementation (with inspection that it is not spec-compliant).

Please update the plugin. I will be very grateful for issues reports.

**Comment by jurgenbrouwer** [comment]
It's looking good @karollewandowski ! I like the warning it gives (because you are right that it's unnatural) and that it no longer marks the complete file as invalid. Great work!
