### ISSUE TITLE
HTL syntax highlighting difficult to read in dark theme

### ISSUE THREAD

**Issue by ericvangeem** [karollewandowski/aem-intellij-plugin#172]
I am using a dark theme for IntelliJ and cannot find a way to change the syntax colors of HTL symbols. In the screenshot below I would like to adjust the colors of `data-sly-*` and the `clientlib` variable for example. I have not been able to find a way to change these colors.

![Screen Shot 2019-05-21 at 5 08 20 PM](https://user-images.githubusercontent.com/1059318/58134035-2cc2b680-7beb-11e9-98fc-862540542071.png)

**Comment by karollewandowski** [comment]
Colors page is implemented in the milestone I'm working on at the very moment :-) I have a few more tasks to finish though and it can take a few weeks.

I'm wondering why you have a dark theme and highlighting from the light one. Please check it in Preferences / Appearance & Behavior / Appearance: Theme. It should be Darcula to have highlighting looking fine on dark background. If it doesn't change colors, try to restart IDE.

**Comment by ericvangeem** [comment]
Thanks Karol. Looks like it is an issue with a custom color scheme I am using. Switching to the Darcula scheme seems to fix it. I will look forward to the release of the colors page!

**Comment by karollewandowski** [comment]
@ericvangeem, colors page has been released in version 0.10.2. Please update the plugin.

**Comment by ericvangeem** [comment]
Thanks Karol, the update looks great!
