### ISSUE TITLE
Breaks default class-path autocomplete feature in IntelliJ

### ISSUE THREAD

**Issue by ConnorJamesLow** [karollewandowski/aem-intellij-plugin#176]
Normally, in IntelliJ, when I start typing a classpath, e.g.

```html
<sly data-sly-use.model="${'com.my.path.
```

IntelliJ gives suggested namespaces/classes that follow the path so I can tab to autocomplete. This feature stops working as soon as I enable the AEM IDE plugin: no suggestions come up whatsoever.

**Comment by karollewandowski** [comment]
Thank you very much for reporting this issue!

It was regression bug introduced in AEM IDE 2022.2.

It's fixed and released now in version 2022.2.2.
Update and enjoy 🙂
