### ISSUE TITLE
AEM IDE Dispatcher .any 'info' issue

### ISSUE THREAD

**Issue by Promathia** [karollewandowski/aem-intellij-plugin#177]
Hi colleagues. Thanks for your work and creation of AEM IDE plugin.
I noticed that the plugin wrongly treats 'info' instruction as an error in dispatcher.any file inside a farm.
This instruction enables dispatcher debugging and is an official one, please check the documentation:
https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html?lang=en#debugging
![image](https://github.com/karollewandowski/aem-intellij-plugin/assets/16146208/4d13abf0-7641-4fa4-997e-326b4be14093)

It would be nice if you could update the plugin and allow this (including promts and validation)

Thanks in advance!

**Comment by karollewandowski** [comment]
Thank you for reporting this issue.

It has been fixed. Please update the plugin to 2023.3.4.

In the future, we will be grateful for reporting errors on https://github.com/aemide/issues/issues.
Thanks!
